### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mmoll** [voxpupuli/puppet-php#168]
@fpletz I think what's there now should be released.

**Comment by fadenb** [comment]
This will be a new major version?
We should coordinate to ensure documentation is up to date as well make sure all core funtionality is working.

**Comment by mmoll** [comment]
for 1: we would need to check parameters and defaults.
for 2: I'd like to remind about #99

**Comment by mmoll** [comment]
also, I think theres should be some search for more maintainers or **maybe** think about giving this to voxpupuli, although I think that's not really to place where a php module belongs to.

**Comment by igalic** [comment]
hello o/~
i am a voxpupuli.
