### ISSUE TITLE
Test current master on Ubuntu

### ISSUE THREAD

**Issue by mmoll** [voxpupuli/puppet-php#209]
The current master of this module should get tested on Ubuntu 14.04 and 16.04 with various PHP versions. Ideally Ubuntu 12.04 could still get tested to stay supported until Q2/2017.

**Comment by mpdude** [comment]
Using it on 14.04 with PHP 5. How exactly can I help?

**Comment by mmoll** [comment]
@mpdude by using the current master and fixing things, if something doesn't work as expected or if something is missing from the documentation, adding it.

**Comment by Ma27** [comment]
Currently moving one of my applications to ubuntu xenial (despite odd bugs in vagrant) and this module as it feels a lot smoother to work with this one than with the previous one I've used.

My ``r10k`` tool pulls the code straight from master and everything seems to be fine when doing php7.
In the next time I'll be able to work more on that and then you'll get a more detailed feedback.

**Comment by mmoll** [comment]
@Ma27 If your vagrant bugs are related to installing/using vagrant plugins on a xenial **host**, use the 1.8.1+dfsg-2 package from yakkety, -2 brings an important fix.

**Comment by Ma27** [comment]
currently using `puppetlabs/ubuntu-16.04-64-puppet` with the master of this module with configs for php 7.0 (https://github.com/Sententiaregum/Sententiaregum/blob/master/Vagrantfile, https://github.com/Sententiaregum/Sententiaregum/tree/master/vagrant).

I disabled `fpm` as I was unsure how to deal with it and apache, but the rest works perfectly fine for me.

**Comment by jk2l** [comment]
Have been using this under 14.04 and 16.04. Everything seem to be fine so far
