### ISSUE TITLE
mark Ubuntu 16.04 as supported and fix its tests

### ISSUE THREAD

**Issue by mmoll** [voxpupuli/puppet-php#221]
Tests need to get extended, as 7.0 is the default on xenial.

**Comment by jkroepke** [comment]
Currently I used this module an xenial. Anyway I have still activated the ppa and I do not have any errors.

**Comment by mmoll** [comment]
The module is working fine, this is about spec tests. See 0ec59d1 resulting in https://travis-ci.org/mmoll/puppet-php/jobs/144319951

**Comment by mmoll** [comment]
GH-412
