### ISSUE TITLE
Puppet struggling with already installed pear libs

### ISSUE THREAD

**Issue by brentclark** [voxpupuli/puppet-php#231]
Good day

Im trying to manage a few pear libs

Here is my code : http://pastebin.com/hYppJJtU

I keep getting this message.

Error: Could not update: Execution of '/usr/bin/pear -D auto_discover=1 upgrade --alldeps Numbers_Words-0.16.4' returned 1: pear/Numbers_Words is already installed and is the same as the released version 0.16.4
upgrade failed
Wrapped exception:
Execution of '/usr/bin/pear -D auto_discover=1 upgrade --alldeps Numbers_Words-0.16.4' returned 1: pear/Numbers_Words is already installed and is the same as the released version 0.16.4
upgrade failed
Error: /Stage[main]/Php/Php::Extension[Numbers_Words]/Package[Numbers_Words]/ensure: change from beta to 0.16.4 failed: Could not update: Execution of '/usr/bin/pear -D auto_discover=1 upgrade --alldeps Numbers_Words-0.16.4' returned 1: pear/Numbers_Words is already installed and is the same as the released version 0.16.4
upgrade failed

Im trying to understand why its trying to install / upgrade, when it picks up its already installed.

This is for Debian Jessie.
PHP version : PHP 5.6.24-0+deb8u1

Thank you.
Brent

**Comment by juniorsysadmin** [comment]
Pastebin link has expired. If still an issue when trying latest master branch, please re-open with Puppet version, Ruby version
