### ISSUE TITLE
Missing local variable 'pipe' on PECL extension installation

### ISSUE THREAD

**Issue by ChrisWiegman** [voxpupuli/puppet-php#242]
On the latest updates yesterday installation fails with the following error:

`Error: Could not set 'present' on ensure: undefined local variable or method `pipe' for Package[pecl-xdebug](provider=pecl):Puppet::Type::Package::ProviderPecl`

For reference here is my config:

`class { '::php':
  ensure       => latest,
  manage_repos => true,
  phpunit      => true,
  extensions   => {
    mysql        => { },
    imagick      => { },
    gd           => { },
    curl         => { },
    memcache     => { },
    mbstring     => { },
    mcrypt       => { },
    xdebug       => {
      zend            => true,
      provider        => 'pecl',
      settings        => {
        'XDEBUG/xdebug.trace_enable_trigger'      => '1',
        'XDEBUG/xdebug.trace_output_dir'          => '/vagrant/user-data/debug',
        'XDEBUG/xdebug.collect_includes'          => '1',
        'XDEBUG/xdebug.collect_params'            => '1',
        'XDEBUG/xdebug.collect_vars'              => '1',
        'XDEBUG/xdebug.collect_return'            => '1',
        'XDEBUG/xdebug.dump_globals'              => '1',
        'XDEBUG/xdebug.idekey'                    => 'VAGRANT_DEBUG',
        'XDEBUG/xdebug.profiler_enable_trigger'   => '1',
        'XDEBUG/xdebug.profiler_output_name'      => 'cachegrind.out.%t-%s',
        'XDEBUG/xdebug.profiler_output_dir'       => '/vagrant/user-data/debug',
        'XDEBUG/xdebug.remote_enable'             => '1',
        'XDEBUG/xdebug.remote_mode'               => 'req',
        'XDEBUG/xdebug.remote_host'               => '192.168.13.1',
        'XDEBUG/xdebug.remote_log'                => '/vagrant/user-data/debug/xdebug-remote.log',
        'XDEBUG/xdebug.remote_port'               => '9000',
        'XDEBUG/xdebug.var_display_max_children'  => '-1',
        'XDEBUG/xdebug.var_display_max_data'      => '-1',
        'XDEBUG/xdebug.var_display_max_depth'     => '-1',
        'XDEBUG/xdebug.max_nesting_level'         => '256',
      },
    },
  },
  settings     => {
    'PHP/memory_limit'        => '256M',
    'PHP/post_max_size'       => '100M',
    'PHP/upload_max_filesize' => '100M',
    'PHP/max_execution_time'  => '90',
  },
}`

**Comment by alexjfisher** [comment]
@ChrisWiegman Hi.  Thanks for reporting your issue.  So far, I've not been able to reproduce.  Can I check a couple of things?  Could you provide your Operating System, puppet version and ruby version please?

Could you also confirm you have the same version of the module in your puppet master's environment?

Thanks.
