### ISSUE TITLE
ubuntu 16.04 php 7

### ISSUE THREAD

**Issue by vietcgi** [voxpupuli/puppet-php#254]
Just wonder why I am getting all these errors though things are working properly.

Thanks

Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-apcu' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-apcu
Error: /Stage[main]/Php/Php::Extension[pecl-apcu]/Package[php-pecl-apcu]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-apcu' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-apcu
Notice: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]: Dependency Package[php-pecl-apcu] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]: Skipping because of failed dependencies
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-geoip' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-geoip
Error: /Stage[main]/Php/Php::Extension[pecl-geoip]/Package[php-pecl-geoip]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-geoip' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-geoip
Notice: /Stage[main]/Php/Php::Extension[memcache]/Package[php-memcache]/ensure: ensure changed 'purged' to 'present'
Info: Php::Extension[memcache]: Scheduling refresh of Service[php7.0-fpm]
Notice: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]: Dependency Package[php-pecl-apcu] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]: Skipping because of failed dependencies
Notice: /Stage[main]/Php/Php::Extension[pecl-apcu]/Exec[/usr/sbin/phpenmod -s ALL pecl-apcu]: Dependency Package[php-pecl-apcu] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-apcu]/Exec[/usr/sbin/phpenmod -s ALL pecl-apcu]: Skipping because of failed dependencies
Notice: /Stage[main]/Php::Phpunit/Exec[download phpunit]/returns: executed successfully
Notice: /Stage[main]/Php::Phpunit/File[/usr/local/bin/phpunit]/mode: mode changed '0644' to '0555'
Notice: /Stage[main]/Php/Php::Extension[pecl-geoip]/Exec[/usr/sbin/phpenmod -s ALL pecl-geoip]: Dependency Package[php-pecl-geoip] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-geoip]/Exec[/usr/sbin/phpenmod -s ALL pecl-geoip]: Skipping because of failed dependencies
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-memcache' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-memcache
Error: /Stage[main]/Php/Php::Extension[pecl-memcache]/Package[php-pecl-memcache]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-memcache' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-memcache

**Comment by jk2l** [comment]
kinda looks like your setting errors. can you give a full settings for your extension param?

**Comment by vietcgi** [comment]
I don't have any extension param setup.  Here is the hiera setup.

php::manage_repos: false
php::params::cfg_root: /etc/php/7.0
php::fpm::config::pid_file: /var/run/php/php7.0-fpm.pid
php::fpm::config::error_log: /var/log/php7.0-fpm.log
php::fpm_service_name: php7.0-fpm
php::ext_tool_enable: /usr/sbin/phpenmod
php::ext_tool_query: '/usr/sbin/phpquery -v 7.0'
php::package_prefix: php-
php::ensure: latest
php::fpm: true
php::dev: true
php::composer: true
php::pear: true
php::phpunit: true
php::settings:
  'PHP/max_execution_time': '90'
  'PHP/max_input_time': '300'
  'PHP/memory_limit': '128M'
  'PHP/post_max_size': '32M'
  'PHP/upload_max_filesize': '32M'
  'Date/date.timezone': 'America/Los_Angeles'

php::fpm::pools:
  www1:
    listen: '/var/run/php7-fpm.sock1'
php::fpm::pools:
  www2:
    listen: '/var/run/php7-fpm.sock2'

**Comment by jk2l** [comment]
you sure you don't have anything like "php::extensions" somewhere? 

how do you declare the class?

**Comment by vietcgi** [comment]
I have include '::php' on the current node.  I also tried the config below on a different node and got pretty much same error.

class { '::php':
    ensure       => latest,
    manage_repos => false,
    fpm          => true,
    dev          => false,
    composer     => true,
    pear         => false,
    phpunit      => false,
    package_prefix =>'php7.0-',
    settings   => {
      'PHP/max_execution_time'  => '90',
      'PHP/max_input_time'      => '300',
      'PHP/memory_limit'        => '128M',
      'PHP/post_max_size'       => '32M',
      'PHP/upload_max_filesize' => '32M',
      'Date/date.timezone'      => 'America/Los_Angeles ',
    },
    extensions => {
      xml       => {},
      gd        => {},
      mcrypt    => {},
      mysqlnd   => {},
      mbstring  => {},
      opcache   => {},
   }
  }

  php::fpm::pool { 'www1':
    listen => '/var/run/php7-fpm.sock1',
  }
  php::fpm::pool { 'www2':
    listen => '/var/run/php7-fpm.sock2',
  }

**Comment by jk2l** [comment]
what is the error for this latest configs. should be different

**Comment by vietcgi** [comment]
It is the same. I don't have those modules enabled but somehow they are there in the logs.


Notice: /Stage[main]/Php/Php::Extension[mysqlnd]/Package[php7.0-mysqlnd]/ensure: ensure changed 'purged' to 'present'
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-apcu' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-apcu
Error: /Stage[main]/Php/Php::Extension[pecl-apcu]/Package[php-pecl-apcu]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php-pecl-apcu' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-apcu
Notice: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]: Dependency Package[php-pecl-apcu] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat_ctime]: Skipping because of failed dependencies
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php7.0-pecl-geoip' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.0-pecl-geoip
E: Couldn't find any package by glob 'php7.0-pecl-geoip'
E: Couldn't find any package by regex 'php7.0-pecl-geoip'
Error: /Stage[main]/Php/Php::Extension[pecl-geoip]/Package[php7.0-pecl-geoip]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php7.0-pecl-geoip' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.0-pecl-geoip
E: Couldn't find any package by glob 'php7.0-pecl-geoip'
E: Couldn't find any package by regex 'php7.0-pecl-geoip'
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php7.0-pecl-memcache' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.0-pecl-memcache
E: Couldn't find any package by glob 'php7.0-pecl-memcache'
E: Couldn't find any package by regex 'php7.0-pecl-memcache'
Error: /Stage[main]/Php/Php::Extension[pecl-memcache]/Package[php7.0-pecl-memcache]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php7.0-pecl-memcache' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.0-pecl-memcache
E: Couldn't find any package by glob 'php7.0-pecl-memcache'
E: Couldn't find any package by regex 'php7.0-pecl-memcache'
Notice: /Stage[main]/Php/Php::Extension[pecl-memcache]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-memcache]: Dependency Package[php7.0-pecl-memcache] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-memcache]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-memcache]: Skipping because of failed dependencies
Notice: /Stage[main]/Php/Php::Extension[pecl-memcache]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-memcache]: Triggered 'refresh' from 1 events
Info: Php::Extension[pecl-memcache]: Scheduling refresh of Service[php7.0-fpm]
Notice: /Stage[main]/Php/Php::Extension[gd]/Package[php7.0-gd]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]: Dependency Package[php-pecl-apcu] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-apcu]/Php::Config[pecl-apcu]/Php::Config::Setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]/Ini_setting[/etc/php/7.0/mods-available/pecl-apcu.ini: apc.stat]: Skipping because of failed dependencies
Notice: /Stage[main]/Php/Php::Extension[pecl-apcu]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-apcu]: Dependency Package[php-pecl-apcu] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-apcu]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-apcu]: Skipping because of failed dependencies
Notice: /Stage[main]/Php/Php::Extension[pecl-apcu]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-apcu]: Triggered 'refresh' from 1 events
Info: Php::Extension[pecl-apcu]: Scheduling refresh of Service[php7.0-fpm]
Notice: /Stage[main]/Php/Php::Extension[pecl-geoip]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-geoip]: Dependency Package[php7.0-pecl-geoip] has failures: true
Warning: /Stage[main]/Php/Php::Extension[pecl-geoip]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-geoip]: Skipping because of failed dependencies
Notice: /Stage[main]/Php/Php::Extension[pecl-geoip]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL pecl-geoip]: Triggered 'refresh' from 1 events
Info: Php::Extension[pecl-geoip]: Scheduling refresh of Service[php7.0-fpm]

**Comment by jk2l** [comment]
you may want to search where is calling "geoip" "memcache"...etc

**Comment by dhoppe** [comment]
You can not set `package_prefix` to `php7.0-`, because the packages `php-pecl-apcu`, `php-pecl-geoip` and `php-pecl-memcache` do  not exist at Ubuntu 16.04, as you can see at  http://packages.ubuntu.com.

You might want set `manage_repos` to `true`, which brings us to the next problem. The version of PHP defaults to `5.6` and can not be changed that easily. :(

**Comment by jk2l** [comment]
no php default for 16.04 is php7, also https://github.com/voxpupuli/puppet-php/blob/master/manifests/extension.pp should use that prefix too.

the thing that puzzle me is where is memcache extensions being added. it is obvious "pecl-geoip" or other stuff being added. and don't seem to be inside the source code.

so i suspect he got the geoip module or other declared somewhere

**Comment by dhoppe** [comment]
@jk2l You are right. I was using Ubuntu 14.04 instead of Ubuntu 16.04. Now everything works as expected and no `php-pecl-*`packages are being installed.

```
node 'default' {
  class { '::php':
    ensure         => latest,
    manage_repos   => false,
    fpm            => true,
    dev            => false,
    composer       => true,
    pear           => false,
    phpunit        => false,
    package_prefix =>'php7.0-',
    settings       => {
      'PHP/max_execution_time'  => '90',
      'PHP/max_input_time'      => '300',
      'PHP/memory_limit'        => '128M',
      'PHP/post_max_size'       => '32M',
      'PHP/upload_max_filesize' => '32M',
      'Date/date.timezone'      => 'America/Los_Angeles',
    },
    extensions     => {
      xml      => {},
      gd       => {},
      mcrypt   => {},
      mysqlnd  => {},
      mbstring => {},
      opcache  => {},
      },
    }

  php::fpm::pool { 'www1':
    listen => '/var/run/php7-fpm.sock1',
  }

  php::fpm::pool { 'www2':
    listen => '/var/run/php7-fpm.sock2',
  }
}
```

```
dhoppe@macbook ~/Projects/vagrant/ubuntu-16.04.1-amd64 (git)-[master] % vagrant provision
==> default: vagrant-r10k: Puppet provisioner module_path is nil, assuming puppet4 environment mode
==> default: vagrant-r10k: Puppet provisioner module_path is nil, assuming puppet4 environment mode
==> default: vagrant-r10k: Puppet provisioner module_path is nil, assuming puppet4 environment mode
==> default: vagrant-r10k: Beginning r10k deploy of puppet modules into /Users/dhoppe/Projects/vagrant/ubuntu-16.04.1-amd64/environments/dev/modules using /Users/dhoppe/Projects/vagrant/ubuntu-16.04.1-amd64/Puppetfile
INFO	 -> Loading modules from Puppetfile into queue
INFO	 -> Deploying php into /Users/dhoppe/Projects/vagrant/ubuntu-16.04.1-amd64/environments/dev/modules
INFO	 -> Deploying stdlib into /Users/dhoppe/Projects/vagrant/ubuntu-16.04.1-amd64/environments/dev/modules
INFO	 -> Deploying inifile into /Users/dhoppe/Projects/vagrant/ubuntu-16.04.1-amd64/environments/dev/modules
INFO	 -> Deploying concat into /Users/dhoppe/Projects/vagrant/ubuntu-16.04.1-amd64/environments/dev/modules
INFO	 -> Deploying apt into /Users/dhoppe/Projects/vagrant/ubuntu-16.04.1-amd64/environments/dev/modules
==> default: vagrant-r10k: Deploy finished
==> default: Configuring cache buckets...
==> default: Running provisioner: puppet...
==> default: Running Puppet with environment dev...
==> default: mesg: ttyname failed: Inappropriate ioctl for device
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Warning: ModuleLoader: module 'php' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> default:    (file & line not available)
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README.
==> default:    (at /tmp/vagrant-puppet/environments/dev/modules/stdlib/lib/puppet/functions/deprecation.rb:19:in `deprecation')
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README.
==> default:    (at /tmp/vagrant-puppet/environments/dev/modules/stdlib/lib/puppet/functions/deprecation.rb:19:in `deprecation')
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README.
==> default:    (at /tmp/vagrant-puppet/environments/dev/modules/stdlib/lib/puppet/functions/deprecation.rb:19:in `deprecation')
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README.
==> default:    (at /tmp/vagrant-puppet/environments/dev/modules/stdlib/lib/puppet/functions/deprecation.rb:19:in `deprecation')
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README.
==> default:    (at /tmp/vagrant-puppet/environments/dev/modules/stdlib/lib/puppet/functions/deprecation.rb:19:in `deprecation')
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README.
==> default:    (at /tmp/vagrant-puppet/environments/dev/modules/stdlib/lib/puppet/functions/deprecation.rb:19:in `deprecation')
==> default: Notice: Compiled catalog for ubuntu-16.vagrant.dev in environment dev in 4.05 seconds
==> default: Info: Applying configuration version '1476355536'
==> default: Notice: /Stage[main]/Apt/File[preferences]/ensure: created
==> default: Info: /Stage[main]/Apt/File[preferences]: Scheduling refresh of Class[Apt::Update]
==> default: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
==> default: Info: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]: Scheduling refresh of Class[Apt::Update]
==> default: Info: Class[Apt::Update]: Scheduling refresh of Exec[apt_update]
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Php::Packages/Package[php7.0-cli]/ensure: created
==> default: Notice: /Stage[main]/Php::Fpm/Package[php7.0-fpm]/ensure: created
==> default: Info: /Stage[main]/Php::Fpm/Package[php7.0-fpm]: Scheduling refresh of Exec[/usr/sbin/phpenmod -v 7.0 -s ALL xml]
==> default: Info: /Stage[main]/Php::Fpm/Package[php7.0-fpm]: Scheduling refresh of Exec[/usr/sbin/phpenmod -v 7.0 -s ALL gd]
==> default: Info: /Stage[main]/Php::Fpm/Package[php7.0-fpm]: Scheduling refresh of Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mcrypt]
==> default: Info: /Stage[main]/Php::Fpm/Package[php7.0-fpm]: Scheduling refresh of Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mysqlnd]
==> default: Info: /Stage[main]/Php::Fpm/Package[php7.0-fpm]: Scheduling refresh of Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mbstring]
==> default: Info: /Stage[main]/Php::Fpm/Package[php7.0-fpm]: Scheduling refresh of Exec[/usr/sbin/phpenmod -v 7.0 -s ALL opcache]
==> default: Info: Computing checksum on file /etc/php/7.0/fpm/php-fpm.conf
==> default: Info: /Stage[main]/Php::Fpm::Config/File[/etc/php/7.0/fpm/php-fpm.conf]: Filebucketed /etc/php/7.0/fpm/php-fpm.conf to puppet with sum d3455864e11f659b5b839acb64fc5531
==> default: Notice: /Stage[main]/Php::Fpm::Config/File[/etc/php/7.0/fpm/php-fpm.conf]/content: content changed '{md5}d3455864e11f659b5b839acb64fc5531' to '{md5}9205e0c5bfa010464f03a4e4a40af3ff'
==> default: Info: /Stage[main]/Php::Fpm::Config/File[/etc/php/7.0/fpm/php-fpm.conf]: Scheduling refresh of Class[Php::Fpm::Service]
==> default: Info: Computing checksum on file /etc/php/7.0/fpm/pool.d/www.conf
==> default: Info: /Stage[main]/Php::Fpm/Php::Fpm::Pool[www]/File[/etc/php/7.0/fpm/pool.d/www.conf]: Filebucketed /etc/php/7.0/fpm/pool.d/www.conf to puppet with sum f0bd7f67ebe9f7ab489a7a2904f33b8b
==> default: Notice: /Stage[main]/Php::Fpm/Php::Fpm::Pool[www]/File[/etc/php/7.0/fpm/pool.d/www.conf]/content: content changed '{md5}f0bd7f67ebe9f7ab489a7a2904f33b8b' to '{md5}ed998964a42b6bc0f7d7a9b355168be9'
==> default: Info: /Stage[main]/Php::Fpm/Php::Fpm::Pool[www]/File[/etc/php/7.0/fpm/pool.d/www.conf]: Scheduling refresh of Class[Php::Fpm::Service]
==> default: Notice: /Stage[main]/Main/Node[default]/Php::Fpm::Pool[www1]/File[/etc/php/7.0/fpm/pool.d/www1.conf]/ensure: defined content as '{md5}8d5ec100dce65cfbd54a8853a022a823'
==> default: Info: /Stage[main]/Main/Node[default]/Php::Fpm::Pool[www1]/File[/etc/php/7.0/fpm/pool.d/www1.conf]: Scheduling refresh of Class[Php::Fpm::Service]
==> default: Notice: /Stage[main]/Main/Node[default]/Php::Fpm::Pool[www2]/File[/etc/php/7.0/fpm/pool.d/www2.conf]/ensure: defined content as '{md5}9c1ffcd5a2abef22d575eab58bb4d508'
==> default: Info: /Stage[main]/Main/Node[default]/Php::Fpm::Pool[www2]/File[/etc/php/7.0/fpm/pool.d/www2.conf]: Scheduling refresh of Class[Php::Fpm::Service]
==> default: Notice: /Stage[main]/Php::Cli/Php::Config[cli]/Php::Config::Setting[/etc/php/7.0/cli/php.ini: PHP/max_execution_time]/Ini_setting[/etc/php/7.0/cli/php.ini: PHP/max_execution_time]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Cli/Php::Config[cli]/Php::Config::Setting[/etc/php/7.0/cli/php.ini: PHP/max_input_time]/Ini_setting[/etc/php/7.0/cli/php.ini: PHP/max_input_time]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Cli/Php::Config[cli]/Php::Config::Setting[/etc/php/7.0/cli/php.ini: PHP/memory_limit]/Ini_setting[/etc/php/7.0/cli/php.ini: PHP/memory_limit]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Cli/Php::Config[cli]/Php::Config::Setting[/etc/php/7.0/cli/php.ini: PHP/post_max_size]/Ini_setting[/etc/php/7.0/cli/php.ini: PHP/post_max_size]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Cli/Php::Config[cli]/Php::Config::Setting[/etc/php/7.0/cli/php.ini: PHP/upload_max_filesize]/Ini_setting[/etc/php/7.0/cli/php.ini: PHP/upload_max_filesize]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Cli/Php::Config[cli]/Php::Config::Setting[/etc/php/7.0/cli/php.ini: Date/date.timezone]/Ini_setting[/etc/php/7.0/cli/php.ini: Date/date.timezone]/ensure: created
==> default: Notice: /Stage[main]/Php::Composer/Exec[download composer]/returns: executed successfully
==> default: Notice: /Stage[main]/Php::Composer/File[/usr/local/bin/composer]/mode: mode changed '0644' to '0555'
==> default: Notice: /Stage[main]/Php/Php::Extension[xml]/Package[php7.0-xml]/ensure: created
==> default: Notice: /Stage[main]/Php/Php::Extension[xml]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL xml]: Triggered 'refresh' from 1 events
==> default: Info: Php::Extension[xml]: Scheduling refresh of Service[php7.0-fpm]
==> default: Notice: /Stage[main]/Php/Php::Extension[gd]/Package[php7.0-gd]/ensure: created
==> default: Notice: /Stage[main]/Php/Php::Extension[gd]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL gd]: Triggered 'refresh' from 1 events
==> default: Info: Php::Extension[gd]: Scheduling refresh of Service[php7.0-fpm]
==> default: Notice: /Stage[main]/Php/Php::Extension[mcrypt]/Package[php7.0-mcrypt]/ensure: created
==> default: Notice: /Stage[main]/Php/Php::Extension[mcrypt]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mcrypt]: Triggered 'refresh' from 1 events
==> default: Info: Php::Extension[mcrypt]: Scheduling refresh of Service[php7.0-fpm]
==> default: Notice: /Stage[main]/Php/Php::Extension[mysqlnd]/Package[php7.0-mysqlnd]/ensure: created
==> default: Notice: /Stage[main]/Php/Php::Extension[mysqlnd]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mysqlnd]: Triggered 'refresh' from 1 events
==> default: Info: Php::Extension[mysqlnd]: Scheduling refresh of Service[php7.0-fpm]
==> default: Notice: /Stage[main]/Php/Php::Extension[mbstring]/Package[php7.0-mbstring]/ensure: created
==> default: Notice: /Stage[main]/Php/Php::Extension[mbstring]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mbstring]: Triggered 'refresh' from 1 events
==> default: Info: Php::Extension[mbstring]: Scheduling refresh of Service[php7.0-fpm]
==> default: Notice: /Stage[main]/Php/Php::Extension[opcache]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL opcache]: Triggered 'refresh' from 1 events
==> default: Info: Php::Extension[opcache]: Scheduling refresh of Service[php7.0-fpm]
==> default: Notice: /Stage[main]/Php::Fpm::Config/Php::Config[fpm]/Php::Config::Setting[/etc/php/7.0/fpm/php.ini: PHP/max_execution_time]/Ini_setting[/etc/php/7.0/fpm/php.ini: PHP/max_execution_time]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Fpm::Config/Php::Config[fpm]/Php::Config::Setting[/etc/php/7.0/fpm/php.ini: PHP/max_input_time]/Ini_setting[/etc/php/7.0/fpm/php.ini: PHP/max_input_time]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Fpm::Config/Php::Config[fpm]/Php::Config::Setting[/etc/php/7.0/fpm/php.ini: PHP/post_max_size]/Ini_setting[/etc/php/7.0/fpm/php.ini: PHP/post_max_size]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Fpm::Config/Php::Config[fpm]/Php::Config::Setting[/etc/php/7.0/fpm/php.ini: PHP/upload_max_filesize]/Ini_setting[/etc/php/7.0/fpm/php.ini: PHP/upload_max_filesize]/value: value changed '[redacted sensitive information]' to '[redacted sensitive information]'
==> default: Notice: /Stage[main]/Php::Fpm::Config/Php::Config[fpm]/Php::Config::Setting[/etc/php/7.0/fpm/php.ini: Date/date.timezone]/Ini_setting[/etc/php/7.0/fpm/php.ini: Date/date.timezone]/ensure: created
==> default: Info: Php::Config[fpm]: Scheduling refresh of Class[Php::Fpm::Service]
==> default: Info: Class[Php::Fpm::Service]: Scheduling refresh of Service[php7.0-fpm]
==> default: Notice: /Stage[main]/Php::Fpm::Service/Service[php7.0-fpm]: Triggered 'refresh' from 7 events
==> default: Notice: Applied catalog in 53.14 seconds
==> default: Configuring cache buckets...
vagrant provision  5.68s user 1.71s system 9% cpu 1:18.19 total
```

```
vagrant@ubuntu-16:~$ dpkg -l | grep php
ii  php-common                         1:35ubuntu6                     all          Common files for PHP packages
ii  php7.0-cli                         7.0.8-0ubuntu0.16.04.3          amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                      7.0.8-0ubuntu0.16.04.3          amd64        documentation, examples and common module for PHP
ii  php7.0-fpm                         7.0.8-0ubuntu0.16.04.3          amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-gd                          7.0.8-0ubuntu0.16.04.3          amd64        GD module for PHP
ii  php7.0-json                        7.0.8-0ubuntu0.16.04.3          amd64        JSON module for PHP
ii  php7.0-mbstring                    7.0.8-0ubuntu0.16.04.3          amd64        MBSTRING module for PHP
ii  php7.0-mcrypt                      7.0.8-0ubuntu0.16.04.3          amd64        libmcrypt module for PHP
ii  php7.0-mysql                       7.0.8-0ubuntu0.16.04.3          amd64        MySQL module for PHP
ii  php7.0-opcache                     7.0.8-0ubuntu0.16.04.3          amd64        Zend OpCache module for PHP
ii  php7.0-readline                    7.0.8-0ubuntu0.16.04.3          amd64        readline module for PHP
ii  php7.0-xml                         7.0.8-0ubuntu0.16.04.3          amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
```

**Comment by vietcgi** [comment]
thanks guys...I got this figured out..I had another php params in common.yaml...which caused these errors.
