### ISSUE TITLE
repo::debian $release

### ISSUE THREAD

**Issue by kwisatz** [voxpupuli/puppet-php#266]
Maybe I misunderstand something, but from what I see in repo/debian.pp the $release is hardcoded to wheezy-php56 and there's no way to change this since php::repo::debian cannot be called directly and $release is not passed on from somewhere else? Wouldn't using $lsbdistcodename work as a default here?

At least, on my server, which runs Debian 8.6, this is trying to add sources for wheezy-php56, even with 
```
class { '::php::globals':
        php_version => '7.0',
        config_root => '/etc/php/7.0',
    }->
    class { '::php':
        ensure       => latest,
        ...
```

Like I said, maybe I'm missing something and I'd just as happily like to be directed to RTFM to learn what I need to change.

**Comment by jk2l** [comment]
use Hiera to overwrite. the module originally written using Hiera to overwrite rather than using parameters from main class.

i think this issues is sort of being mentioned in https://github.com/voxpupuli/puppet-php/issues/222

**Comment by kwisatz** [comment]
Thanks, I'll give it a try!

**Comment by kwisatz** [comment]
Confirming that this works.
