### ISSUE TITLE
Error: undefined method `ref' for nil:NilClass

### ISSUE THREAD

**Issue by ChrisWiegman** [voxpupuli/puppet-php#275]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.4.3
- Ruby: 1.9.3
- Distribution: Ubuntu 14.04
- Module version: bc912d1577f3b9ac23ec1e72a87d9e7c4a702f75

### How to reproduce (e.g Puppet code you use)

class { '::php':
  ensure       => latest,
  manage_repos => true,
  phpunit      => true,
  extensions   => {
    xml          => { },
    mysql        => { },
    imagick      => { },
    gd           => { },
    curl         => { },
    memcache     => { },
    ldap         => { },
    opcache      => {
      zend => true,
    },
    mbstring     => { },
    soap         => { },
    mcrypt       => { },
    xdebug       => {
      zend            => true,
      settings        => {
        'XDEBUG/xdebug.trace_enable_trigger'      => '1',
        'XDEBUG/xdebug.trace_output_dir'          => '/vagrant/user-data/debug',
        'XDEBUG/xdebug.collect_includes'          => '1',
        'XDEBUG/xdebug.collect_params'            => '1',
        'XDEBUG/xdebug.collect_vars'              => '1',
        'XDEBUG/xdebug.collect_return'            => '1',
        'XDEBUG/xdebug.dump_globals'              => '1',
        'XDEBUG/xdebug.idekey'                    => 'VAGRANT_DEBUG',
        'XDEBUG/xdebug.profiler_enable_trigger'   => '1',
        'XDEBUG/xdebug.profiler_output_name'      => 'cachegrind.out.%t-%s',
        'XDEBUG/xdebug.profiler_output_dir'       => '/vagrant/user-data/debug',
        'XDEBUG/xdebug.remote_enable'             => '1',
        'XDEBUG/xdebug.remote_mode'               => 'req',
        'XDEBUG/xdebug.remote_host'               => '192.168.22.1',
        'XDEBUG/xdebug.remote_log'                => '/vagrant/user-data/debug/xdebug-remote.log',
        'XDEBUG/xdebug.remote_port'               => '9000',
        'XDEBUG/xdebug.var_display_max_children'  => '-1',
        'XDEBUG/xdebug.var_display_max_data'      => '-1',
        'XDEBUG/xdebug.var_display_max_depth'     => '-1',
        'XDEBUG/xdebug.max_nesting_level'         => '256',
      },
    },
  },
  settings     => {
    'PHP/memory_limit'        => '256M',
    'PHP/post_max_size'       => '100M',
    'PHP/upload_max_filesize' => '100M',
    'PHP/max_execution_time'  => '90',
  },
} 

### What are you seeing
Vagrant failure with the following error
Error: undefined method `ref' for nil:NilClass

### What behaviour did you expect instead
Provisioning of PHP to complete

### Output log
Running Puppet with init.pp...
==> ouroboros: Error: undefined method `ref' for nil:NilClass on node ouroboros
==> ouroboros: Error: undefined method `ref' for nil:NilClass on node ouroboros
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

### Any additional information you'd like to impart

reverting to a8c113e42dfc91dff602b35cf3858292e7c7e149 fixes the issue

**Comment by alexjfisher** [comment]
I think you're hitting https://tickets.puppetlabs.com/browse/PUP-1597

@ChrisWiegman Are you able to upgrade to puppet 3.8?

**Comment by ChrisWiegman** [comment]
Negative. This is using the default puppet in the recommended Vagrant box for the bistro (bento/ubuntu-14.04)

Chris Wiegman https://www.chriswiegman.com <https://www.chriswiegman.com/> | @ChrisWiegman <https://twitter.com/ChrisWiegman>

**Comment by bastelfreak** [comment]
Hi @ChrisWiegman 

thanks for rising up this issue. I am sorry but I don't think we will be fixing this for a couple of reasons:

* Ubuntu 14.04 is really old. It is still supported by canonical but everybody should upgrade to latest 16.04 LTS
* Ruby1.9.3 is EOL since a long time and should not be used in production anymore
* Puppet3 support will end in 30 days

You can easily workaround by using puppet3.8 which works with this module. If you are forced to use the outdated platform you can still use an older release.
