### ISSUE TITLE
how to disable default www FPM pool?

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-php#288]
I am using FPM pools which I manually configure on the server directly, so I would like to disable the default `www` pool in my hiera node config. For that purpose I tried:

`php::fpm::pools: {}` or even `php::fpm::pools: null`

but unfortunately they don't work. So my question here is: is it possible to disable the default `www` pool and if yes how?

Cheers!

**Comment by simonasr** [comment]
you can disable fpm pools by setting in Hiera:

```
php::fpm::pools:
  www:
    ensure: 'absent'
```

**Comment by hostingnuggets** [comment]
Thanks @simonasr, that worked perfectly!
