### ISSUE TITLE
Stable 4.x release soon?

### ISSUE THREAD

**Issue by thaiphv** [voxpupuli/puppet-php#295]
When will 4.x stable be released?

**Comment by igalic** [comment]
whelp… 4.x is released, i wouldn't call it stable yet xD

**Comment by thaiphv** [comment]
@igalic so do we plan to make a stable release soon?

**Comment by igalic** [comment]
@thaiphv tbh, just having idempotence (#307) would be a great start

**Comment by thaiphv** [comment]
[v4.0.0](https://github.com/voxpupuli/puppet-php/releases/tag/v4.0.0) was released on 12 Feb so I think I don't need to keep this issue open anymore.

**Comment by anlutro** [comment]
4.0.0 is not on forge, though. Only 4.0.0-beta1.
