### ISSUE TITLE
Ubuntu 16 mysql extension so name with packages from ondrej PPA

### ISSUE THREAD

**Issue by spaulg** [voxpupuli/puppet-php#309]
Using Ubuntu 16.04 LTS with the PHP builds from https://launchpad.net/~ondrej/+archive/ubuntu/php, the mysql extension installs the so files mysqli, mysqlnd and pdo_mysql.

The Puppet module automatically creates an extension ini file named after the extension itself. However mysql.so does not exist. Whilst an option is available to change the so name, not one but three so files are installed.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9.0
- Ruby: ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
- Distribution: Ubuntu 16.04 LTS
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)
Add the extension for mysql. I use hiera to achieve this:

php::extensions:
  mysql: {}

## What are you seeing
The puppet module initialises a php extension ini file for the mysql extension, however the extension contains 3 so files for mysqli, mysqlnd and pdo_mysql. Whilst the module has support to override the so name, it can't override all 3.

## What behaviour did you expect instead
The ability to disable generating an ini file in the puppet extension manifest. Optionally allowing custom ini files to be dropped in to place using the php::config manifest via the main init.pp script and via hiera.

**Comment by tdm4** [comment]
I can confirm this is the same in Ubuntu 14.04

**Comment by igalic** [comment]
i've believe to have fixed this in master https://github.com/voxpupuli/puppet-php/pull/315

**Comment by Vincent--** [comment]
Hmm, I think the module should be able to manage 3 different names...

For instance, for apcu-bc from ppa ondrej on Ubuntu:
1/ package name: php-apcu-bc
2/ ini file name: apcu_bc.ini (see the underscore)
3/ so name: apc.so

**Comment by tdm4** [comment]
See PR #330 .. which should stop mysql.ini form being created on an Ubuntu machine with PHP 7.0/7.1 on it.

**Comment by slopokeit** [comment]
Workaround is to use the extension:
```  
extensions => {
  mysqli => {},
}
```

**Comment by hboetes** [comment]
when using mysqli => {},
mysqli is being installed over and over again:
```
Notice: /Stage[main]/Php/Php::Extension[mysqli]/Php::Extension::Install[mysqli]/Package[php7.0-mysqli]/ensure: created
```

Without it the invalid file `/etc/php/7.0/mods-available/mysql.ini` is being created.
```
Notice: /Stage[main]/Php/Php::Extension[mysql]/Php::Extension::Config[mysql]/Php::Config[mysql]/Php::Config::Setting[/etc/php/7.0/mods-available/mysql.ini: extension]/Ini_setting[/etc/php/7.0/mods-available/mysql.ini: extension]/ensure: created
```
Since there is no mention of mysql in puppet-php it seems like the code is a bit too clever by assuming all packages create a shared object with their own name, which isn't the case for mysql.

**Comment by tdm4** [comment]
@hboetes @slopokeit That's because mysqli has been removed from PHP 7.0 and later. (It only exists in 5.6)

Adding the ```mysqli => {}``` is a bad idea.
My diff is a better solution.

**Comment by hboetes** [comment]
@tdm4 
Thanks for the heads up, I just tried your version, and it fails with:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: '::php::config' at /etc/puppetlabs/code/modules/php/manifests/cli.pp:22:3 on node
```
This is on xenial.
