### ISSUE TITLE
Add support for installing multiple php versions/extension

### ISSUE THREAD

**Issue by jg-development** [voxpupuli/puppet-php#311]
The php repo allows to install php 5.6 7.0 and 7.1 parallel.
It would be nice if the module itself allows to install these version parallel.

Is this feature possible in future versions?
Greetings Jan

**Comment by mpdude** [comment]
*metoo*

**Comment by jg-development** [comment]
This feature would be nice

**Comment by tsfoer** [comment]
I'd really appreciate such feature

**Comment by bastelfreak** [comment]
Hey people. We got the same discussion in https://github.com/voxpupuli/puppet-php/issues/448. I'm going to close this issue. Please take a look at https://github.com/voxpupuli/puppet-php/issues/448 comment with your thoughts.
