### ISSUE TITLE
Error: Syntax error at 'String'; expected 

### ISSUE THREAD

**Issue by jcalles** [voxpupuli/puppet-php#324]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## What are you seeing
Error: Syntax error at 'String'; expected ')' at /etc/puppet/modules/php/manifests/extension.pp:56 on node

**Comment by alexjfisher** [comment]
What version of puppet are you using?  This module no longer supports puppet 3.

**Comment by dandunckelman** [comment]
Right, this is probably an error from Puppet 3.x

**Comment by jcalles** [comment]
puppet --version
3.8.5

**Comment by jcalles** [comment]
pupppet opensource Ubuntu 16.04

**Comment by NinjaNate** [comment]
I have this issue as well. Puppet version 3.4.3, Ubuntu 14.04.

**Comment by alexjfisher** [comment]
@jcalles If you need any help migrating to puppet 4, there are always lots of happy people willing to assist on the #voxpupuli IRC channel
