### ISSUE TITLE
Deprecate mayflower/php in favor for voxpupuli/php

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-php#348]
following #183, we should open a Jira ticket to have mayflower/php point to voxpupuli/php.

(or, have the pmt team implement the equivalent of [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) ;)

**Comment by SimonHoenscheid** [comment]
Who can do this?

**Comment by SimonHoenscheid** [comment]
Module is deprecated
