### ISSUE TITLE
Error: Could not upgrade module 'puppet-php' (v4.0.0 -> v5.0.0)

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-php#378]
On my puppet 4.8.2 Debian 9 master server I am trying to upgrade the puppet-php module to v4.0.0 to v5.0.0 with the following command:

`sudo puppet module upgrade --version 5.0.0 puppet-php`

unfortunately it fails with the following output:

```
Notice: Preparing to upgrade 'puppet-php' ...
Notice: Found 'puppet-php' (v4.0.0) in /etc/puppet/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not upgrade module 'puppet-php' (v4.0.0 -> v5.0.0)
  No version of 'puppet-php' can satisfy all dependencies
    Use `puppet module upgrade --ignore-dependencies` to upgrade only this module
```

It must conflict with another puppet module but I can't figure out which one. I have the following modules installed:

```
/etc/puppet/code/environments/production/modules
├── darin-zypprepo (v1.0.2)
├── dhoppe-fail2ban (v1.3.4)
├── edestecd-clamav (v1.0.0)
├── example42-puppi (v2.2.3)
├── example42-yum (v2.1.28)
├── fraenki-proftpd (v1.0.0)
├── pdxcat-nrpe (v2.1.1)
├── puppet-archive (v2.0.0)  
├── puppet-extlib (v1.1.0)
├── puppet-nginx (v0.7.1)
├── puppet-php (v4.0.0)
├── puppet-staging (v2.2.0)
├── puppetlabs-apache (v2.0.0)
├── puppetlabs-apt (v4.1.0)  
├── puppetlabs-concat (v4.0.1)
├── puppetlabs-inifile (v1.6.0)
├── puppetlabs-mysql (v3.11.0)
├── puppetlabs-postgresql (v5.1.0)
├── puppetlabs-stdlib (v4.19.0)
├── puppetlabs-tagmail (v2.2.0)
├── razorsedge-snmp (v3.8.1)
├── saz-locales (v2.4.0)
└── stahnma-epel (v1.2.2)
```

any idea what could be wrong?

**Comment by ekohl** [comment]
I wonder if it checks the supported OS since Debian 9 is not in metadata.json.

**Comment by hostingnuggets** [comment]
Is it then safe to upgrade the package with the `--force` parameter? and would be great if that package also natively works with Debian 9 which is already out since around 3 months.

**Comment by djl** [comment]
This doesn't appear to be a Debian-specific issue. I'm seeing the same issue on CentOS 7.

**Comment by ekohl** [comment]
I think that in your case you need https://github.com/voxpupuli/puppet-php/commit/4fdc9a223f2a72634e3e46d2aaa8178c55862a0f in a release. That allows your installed puppet-archive 2.0.0.

@dhollinger could you look at doing a 5.1.0 release?

**Comment by hostingnuggets** [comment]
great that the cause could be found in the metadata.json file, looking forward to test 5.1.0.

**Comment by hostingnuggets** [comment]
@ekohl version 5.1.0 is now out but I don't see any support for Debian 9 in `metadata.json` Is it possible you forgot to add it or is Debian 9 officially still not supported?

**Comment by hostingnuggets** [comment]
any news?

**Comment by ekohl** [comment]
This very much slipped my radar. Since I don't use PHP or this module, it really needs more maintainers to take care of this module. I'd be happy to help someone get up to speed with it but I don't have the time to maintain this module.

**Comment by hostingnuggets** [comment]
@ekohl does this mean that you are actually the only person working on this module?

**Comment by ekohl** [comment]
Not sure. Voxpupuli does rely on users to contribute since it's a pure community effort. Given the number of open issues and PRs this module does need people to step up.

**Comment by SimonHoenscheid** [comment]
This has gone into a release, please close

**Comment by hostingnuggets** [comment]
@SimonHoenscheid the puppet metadata for this package still lists only Debian 7 and 8 as supported, maybe it has been forgotten to update this package file to list Debian 9?

**Comment by bastelfreak** [comment]
@hostingnuggets https://github.com/voxpupuli/puppet-php/pull/440 adds debian 9 support. This is curerntly in our master branch and will be released in the next days.

**Comment by hostingnuggets** [comment]
@bastelfreak great thanks, I will then wait for this new release and test it. I will re-open this case if there should be anything going wrong with the upgrade.
