### ISSUE TITLE
composer handling

### ISSUE THREAD

**Issue by globin** [voxpupuli/puppet-php#4]
Create a utility for composer to:
- [ ] install composer packages globally (e.g PHPUnit)
- [ ] run composer install/update in a directory to handle project dependencies

**Comment by mbrodala** [comment]
I'd suggest not adding this here and reinvent the wheel. There are a few existing solutions which do this quite well.

**Comment by Ma27** [comment]
@mmoll is this still relevant?
I started working on something similiar. If needed, I'd try to finish this somehow in the next time: https://github.com/willdurand/puppet-composer/issues/15

**Comment by mmoll** [comment]
If this can be handled in a seperate module without clashes, we can ommit that here, IMHO.

**Comment by igalic** [comment]
there's also @brainsware / [composer](https://github.com/Brainsware/puppet-composer)
