### ISSUE TITLE
Upgrade to work with Puppet5

### ISSUE THREAD

**Issue by Craige** [voxpupuli/puppet-php#406]
Can we upgrade this repo to work with Puppet5?

**Comment by alexjfisher** [comment]
Is there something specific that doesn't work, or do you just mean updating the metadata.json to mark the module as puppet 5 compatible?

**Comment by Craige** [comment]
Not sure if anything doesn't work. Based on the dependencies I would think everything would work with Puppet5, but we should update the metadata and try it.

**Comment by c33s** [comment]
hope this module stays puppet4 compatible

**Comment by alexjfisher** [comment]
@c33s There are no plans to remove puppet 4 compatibility.

**Comment by alexjfisher** [comment]
@joekohlsdorf Thanks for the feedback and PR.
