### ISSUE TITLE
Is it possible to install a pear package with this module?

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-php#411]
I would like to know if it also possible to install a pear package with this module? I did not find anything in the documentation. If yes could it be possible to document how to do that?

As an example I would like to install the Net_IDNA2 module and manually I would run this command: 

`pear install Net_IDNA2-0.2.0`

**Comment by joekohlsdorf** [comment]
Yes! Untested sample code:
```
class { '::php::extension::install':
  Net_IDNA2   => {
    ensure              => '0.2.0',
    package_prefix => '',
    provider            => 'pear',
  }
}
```

See the code for documentation and options:
https://github.com/voxpupuli/puppet-php/blob/master/manifests/extension/install.pp
https://github.com/voxpupuli/puppet-php/blob/master/manifests/extension/config.pp

**Comment by hostingnuggets** [comment]
@joekohlsdorf thanks that worked, here is an example using a hiera YAML file with the Net_IDNA pear package:
```
php::extensions:
  Net_IDNA: { ensure: 'beta', package_prefix: '', provider: 'pear' }
```
Do you have an idea if it is possible with the `php::extensions` of this module to install the php-db Debian/Sury package? This package is basically the DB pear package  (Database Abstraction Layer) which is bundled in an official .deb package on Debian. I would normally simply install it with `apt-get install php-db`.

**Comment by joekohlsdorf** [comment]
Packages can be installed with `php::packages`:
```
php::packages:
  php-db:
    ensure: 'latest'
```

**Comment by hostingnuggets** [comment]
Thanks for the hiera sample, I added that to my hiera yaml file for this node but nothing happens. I must say I had php-db installed before and quickly removed it using `dpkg -P php-db` but still nothing happens (no changes from the puppet agent).

**Comment by bryangwilliam** [comment]
@hostingnuggets I think the example above needs to be modified a little to have the desired effect: 
```
php::packages::names:
  - php-db
```

**Comment by SimonHoenscheid** [comment]
@hostingnuggets can we close this?

**Comment by hostingnuggets** [comment]
Last note: this should be documented somewhere.
