### ISSUE TITLE
New Release after Ubuntu 18.04 support is added?

### ISSUE THREAD

**Issue by SimonHoenscheid** [voxpupuli/puppet-php#442]
Will there be a new release after Ubuntu 18.04 support is merged?

**Comment by bastelfreak** [comment]
sure. I just need to check through the other open PRs and see what we can include as well. Any help is appreciated :)

**Comment by SimonHoenscheid** [comment]
Can you compile a list which ones you would like to include?

**Comment by bastelfreak** [comment]
We need to check through all open PRs, check if anything can be merged, if anything can be merged with a simple rebase and otherwise we need to ping the creators of the PR again.
