### ISSUE TITLE
Remove hard dependency from apt-transport-https

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-php#454]
Hi,

https://github.com/voxpupuli/puppet-php/blob/3e00b528ea0f29d0a37351f6b27b10be2864f0fd/manifests/repo/debian.pp#L95

since apt-transport-https is in Ubuntu 18.04/Debian 10 just a transitional package it isn't mandatory anymore, the `apt-transport-https` dependency should be conditional.

Since [puppetlabs-apt](https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/source.pp#L32) handle this correctly you should just consume it instead manage it self. 

See:
* https://packages.ubuntu.com/bionic/apt-transport-https
* https://packages.debian.org/buster/apt-transport-https

**Comment by bastelfreak** [comment]
Hi @jkroepke, thanks for raising this issue. Can you provide PR for it?

**Comment by jkroepke** [comment]
@bastelfreak I would like to do but unlike other voxpupuli repositories the process / responsiveness of PR here are way too slow for my taste. Sorry.

**Comment by hostingnuggets** [comment]
Am I getting hit by this?

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Package[apt-transport-https] => Apt::Source[source_php_71] => Package[apt-transport-https])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

**Comment by juniorsysadmin** [comment]
Related to #285

**Comment by TuningYourCode** [comment]
Already resolved by https://github.com/voxpupuli/puppet-php/pull/494 
This issue could be closed.
