### ISSUE TITLE
Why does dotdeb APT wheezy 5.6 repo get installed on Debian 9?

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-php#458]
Hello,

I am using the following hiera node config in order to install PHP 7.1 from the sury repo on a Debian 9 server:

```
php::globals::php_version: '7.1'
php::manage_repos: true
php::repo::debian::dotdeb: false
```

and noticed that this also installs the dotdeb APT repo for wheeezy PHP 5.6 as you can see in the `/etc/apt/sources.list.d/source_php_wheezy-php56.list` file:

```
# This file is managed by Puppet. DO NOT EDIT.
# source_php_wheezy-php56
deb http://packages.dotdeb.org wheezy-php56 all
```

Is this required? or is it a bug maybe?

I am using puppet 4.8.2 on Debian 9 servers and the latest version of this forge module (v.5.3.0).

Thanks

**Comment by bastelfreak** [comment]
This is indeed a bug. Can you provide a patch for this, or an acceptance test that fails?

**Comment by hostingnuggets** [comment]
@bastelfreak sorry I am no dev but I can tell you what I did as a workaround is to comment out all the code/lines which mention the `wheezy-php56` dotdeb repo in the `manifests/repo/debian.pp` as I don't use the dotdeb repo.
