### ISSUE TITLE
Cannot declare both php and php::cli classes

### ISSUE THREAD

**Issue by sunnz** [voxpupuli/puppet-php#489]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.x
- Distribution: CentOS 7.x
- Module version: 6.0.1

## How to reproduce (e.g Puppet code you use)

```
class profile::php {
  class { '::php':
    ensure       => latest,
    manage_repos => false,
    fpm          => true,
    dev          => true,
    composer     => true,
    pear         => true,
    phpunit      => false,
    settings => {
      'PHP/max_execution_time' => '60',
      'PHP/memory_limit'       => '256M',
    },
  }

  class { '::php::cli':
    settings => {
      'PHP/max_execution_time' => '0',
      'PHP/memory_limit'       => '1000M',
    },
  }
}
```

## What are you seeing

Duplicate declaration: Class[Php::Cli] is already declared.

## What behaviour did you expect instead

``max_execution_time`` set to ``60`` and ``memory_limit`` set to ``256M`` in ``/etc/php.ini`` and ``/etc/php-fpm.ini``.

``max_execution_time`` set to ``0`` and ``memory_limit`` set to ``1000M`` in ``/etc/php-cli.ini``.

## Output log

``Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Php::Cli] is already declared at (file: /etc/puppetlabs/code/environments/production/modules/php/manifests/init.pp, line: 164); cannot redeclare (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/php.pp, line: 16) (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/php.pp, line: 16, column: 3) on node test-web``

## Any additional information you'd like to impart

It seems like ``php::cli`` is being declared inside ``php`` class, so I cannot redeclare it. But the ``php`` class just pass the same options to ``php::cli``.

How do I specify default settings for PHP and only override some of those for PHP CLI?

**Comment by sunnz** [comment]
Currently my workaround is as follows:

```
class profile::php {
  class { '::php':
    ensure       => latest,
    manage_repos => false,
    fpm          => true,
    dev          => true,
    composer     => true,
    pear         => true,
    phpunit      => false,
    settings => {
      'PHP/max_execution_time' => '60',
      'PHP/memory_limit'       => '256M',
    },
  }
  -> ini_setting { 'php/cli/memory_limit':
    ensure  => present,
    path    => '/etc/php-cli.ini',
    section => 'PHP',
    setting => 'memory_limit',
    value   => '1000M',
  }
}
```

The downside is that Puppet now writes 256M and then rewrites 1000M on every run.

**Comment by bastelfreak** [comment]
Hi @sunnz, we currently don't support different settings for CLI vs non-CLI. Are you interested in providing a patch for this?

**Comment by sunnz** [comment]
Please see patch: https://github.com/voxpupuli/puppet-php/commit/97ae907c969e0d7897fd26e7abff0142e7ddbae5.diff

Which I have created a pull request #491 for it too.

Thanks!
