### ISSUE TITLE
Extension mysqli causes php7-fpm to reload

### ISSUE THREAD

**Issue by bassdphar** [voxpupuli/puppet-php#497]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.8
- Ruby:
- Distribution: Ubuntu 16.04
- Module version: 6.0.2

## How to reproduce (e.g Puppet code you use)
class profiles::php7 {
# include ::apt because of a bug in php-module.
  include ::apt

# We need  at least php7.0 php7.0-fpm php7.0-gd php7.0-xml php7.0-mbstring libgd-dev composer.

  class { '::php::globals':
    php_version => '7.0',
  }->
  class { '::php':
    ensure       => 'present',
    manage_repos => false,
    fpm          => true,
    dev          => true,
    composer     => true,
    pear         => true,
    phpunit      => false,
    fpm_user  => 'www-data',
    fpm_group => 'www-data',
    #require => [User['www-data']],
    extensions => {
      mbstring => { },
      curl => { },
      gd => { },
      xmlrpc => { },
      bcmath => { },
      zip => { },
      mysqli => { },
      # redis => { },
      mcrypt => { },
      intl => { },
      soap => { },
      sqlite3 => { },
    },
    #  settings   => {
    #    'PHP/max_execution_time'  => '30',
    #  },
  }
  php::fpm::pool { 'common':
    # http://php.puppet.mayflower.de/php/fpm/pool.html
    ensure => 'present',
    listen => '/var/run/php-fpm-common.sock',
    listen_owner => 'www-data',
    listen_group => 'www-data',
  }
}

## What are you seeing
php7-fpm is triggered to restart every time puppet agent is run.
The restart is triggered by installation of extension mysqli for every puppet agent run.
No other extension i am using are causing the same issue.
## What behaviour did you expect instead
Installation of modul once.
## Output log
Notice: /Stage[main]/Php/Php::Extension[mysqli]/Php::Extension::Install[mysqli]/Package[php7.0-mysqli]/ensure: created
Info: Php::Extension::Install[mysqli]: Scheduling refresh of Php::Extension::Config[mysqli]
Info: Php::Extension::Config[mysqli]: Scheduling refresh of Php::Config[mysqli]
Info: Php::Extension::Config[mysqli]: Scheduling refresh of Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mysqli]
Info: Php::Config[mysqli]: Scheduling refresh of Php::Config::Setting[/etc/php/7.0/mods-available/mysqli.ini: extension]
Info: Php::Config::Setting[/etc/php/7.0/mods-available/mysqli.ini: extension]: Scheduling refresh of Ini_setting[/etc/php/7.0/mods-available/mysqli.ini: extension]
Notice: /Stage[main]/Php/Php::Extension[mysqli]/Php::Extension::Config[mysqli]/Php::Config[mysqli]/Php::Config::Setting[/etc/php/7.0/mods-available/mysqli.ini: extension]/Ini_setting[/etc/php/7.0/mods-available/mysqli.ini: extension]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Php/Php::Extension[mysqli]/Php::Extension::Config[mysqli]/Exec[/usr/sbin/phpenmod -v 7.0 -s ALL mysqli]: Triggered 'refresh' from 1 event
Info: Php::Extension[mysqli]: Scheduling refresh of Service[php7.0-fpm]
Notice: /Stage[main]/Php::Fpm::Service/Service[php7.0-fpm]: Triggered 'refresh' from 1 event
Notice: Applied catalog in 3.47 seconds

**Comment by c33s** [comment]
i assume that this is because of the naming change of the mysql extension, see #432 this PR should also fix it for you but i had no time to fix the tests.
