### ISSUE TITLE
php module is not using hiera deep merge anymore.

### ISSUE THREAD

**Issue by schlitzered** [voxpupuli/puppet-php#500]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Ruby: ???
- Distribution:???
- Module version: 6.0.2

## How to reproduce (e.g Puppet code you use)
use hiera to configure php::extensions

## What are you seeing
hiera is not deep merging anymore

## What behaviour did you expect instead
hiera should deep merge php:extensions, as well as for all other lookups

## Any additional information you'd like to impart

the relevant pull request is this one: [commit](https://github.com/voxpupuli/puppet-php/commit/b1888888ce255460fac311c48706033a56194e81)

this basically makes merging using hiera impossible, please revert this as soon as possible or explain

**Comment by schlitzered** [comment]
it is a little bit unfortunate that this change has not made it into the changelog :-/

i will adjust my hiera yaml to include the lookup_options you suggested.

**Comment by arkadicolson** [comment]
I'm still having the issue that php::settings is not merged into php::fpm::settings
Any idea why? In 4.0.0 this was working...
