### ISSUE TITLE
Fpm config results in "expects a Hash value, got Tuple"

### ISSUE THREAD

**Issue by fabbks** [voxpupuli/puppet-php#536]
## Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 5.5
- Ruby: 2.4
- Distribution: Debian 10 (buster)
- Module version: 7.0.0

## How to reproduce (e.g Puppet code you use)
In the manifest:
```puppet
  include ::php
```
In the hiera config:
```hiera
php::fpm::pools:
  www:
    listen: '/var/run/php-fpm.sock'
    listen_owner: 'www-data'
    listen_group: 'www-data'
    pm_max_children: '100'
    pm_status_path: '/fpmstatus'
```

## What are you seeing
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Found value has wrong type, expects a Hash value, got Tuple (file: /etc/puppetlabs/code/environments/php
update/modules/php/manifests/fpm.pp, line: 103, column: 17)

## What behaviour did you expect instead
The pool config should have been pushed to the node. Whatever I change to the hiera config, it always ends with the same error.

## Output log
See above

## Any additional information you'd like to impart
This behaviour is seen since the new module version is released. With the old version there are no issues.

**Comment by smoeding** [comment]
I can confirm this. Line 103 in `manifests/fpm.pp` looks like this:
```
$real_pools = lookup('php::fpm::pools', Hash, {'strategy' => 'unique'}, $pools)
```

The merge strategy `unique` is for array parameters only. But the `lookup` function wants a `Hash`. See the documentation (https://puppet.com/docs/puppet/5.2/hiera_use_function.html):

> 'unique' (called “array merge” in classic Hiera) — Combines any number of arrays and scalar values to return a merged, flattened array with all duplicate values removed. The lookup will fail if any hash values are found.

The lookup should return a hash since the value is used as parameter for `create_resources`.

I would suggest to use the `deep` merge strategy instead.

**Comment by olevole** [comment]
Same issue

**Comment by cubiclelord** [comment]
We are also seeing this bug. Any chance for a quick fix/release? :)
