### ISSUE TITLE
(Old?) Documentation is not available

### ISSUE THREAD

**Issue by riher** [voxpupuli/puppet-php#577]
For example, http://php.puppet.mayflower.de/php/extension.html ist not available anymore. Can it be found somewhere else?

How to reproduce: Go to https://forge.puppet.com/puppet/php or https://github.com/voxpupuli/puppet-php and find non-working links.

**Comment by SimonHoenscheid** [comment]
@bastelfreak  Is there a plan to serve puppet docs somewhere?
