### ISSUE TITLE
Support for Ondřej Surýs PPA on Ubuntu 18.04

### ISSUE THREAD

**Issue by tarjei** [voxpupuli/puppet-php#586]
Hi, I think this is mostly a support request, but we'll see how it goes :)

How do I configure puppet-php to use Surys PPA to fetch a newer version? I tried reading the sourcecode but could not get to the bottom of this.

**Comment by igalic** [comment]
it seems to me that all you have to do is

```puppet
include php::repo::ubuntu
```

**Comment by tarjei** [comment]
I will try that and report back. Thanks @igalic :)
