### ISSUE TITLE
Potential vulnerabilities in Puppet files: Hard-coded Secret

### ISSUE THREAD

**Issue by cantebigene** [voxpupuli/puppet-php#593]
11 hard-coded secrets were found in 3 different scripts.

Script 1: https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/params.pp
 - Line [48](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/params.pp#L48): `fpm_user=www-data`
 - Line [96](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/params.pp#L96): `fpm_user=wwwrun`
 - Line [163](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/params.pp#L163): `fpm_user=apache`
 - Line [192](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/params.pp#L192): `fpm_user=www`
 - Line [218](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/params.pp#L218): `fpm_user=root`

Script 2: https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/repo/redhat.pp
 - Line [22](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/repo/redhat.pp#L22): `gpgkey=https://rpms.remirepo.net/rpm-gpg-key-remi`
 - Line [31](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/repo/redhat.pp#L31): `gpgkey=https://rpms.remirepo.net/rpm-gpg-key-remi`

Script 3: https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/extension/config.pp
 - Line [63](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/extension/config.pp#L63): `extension_key=zend_extension`
 - Line [69](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/extension/config.pp#L69): `extension_key=extension`
 - Line [83](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/extension/config.pp#L83): `extension_key==>`
 - Line [117](https://github.com/voxpupuli/puppet-php/blob/f4465f47c3126f3f40d26327169d17207aaca1b1/manifests/extension/config.pp#L117): `extension_key=and`

A secret can be a password, user name, or private cryptographic key. 

This type of smell can lead to well-known types of vulnerabilities, as documented by CWE ([CWE-798](https://cwe.mitre.org/data/definitions/798.html) and [CWE-259](https://cwe.mitre.org/data/definitions/259.html)). Hard-coded secrets can be used to bypass protection mechanisms, gain privileges on applications and access to sensitive data. 

Storing secrets in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
To protect/manage your secrets, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your secrets by variables from the vault. For instance, replace`$password = ‘12345’` by `$password = $vault::password`. Thus, your secrets will no longer be disclosed publicly.

**Comment by c33s** [comment]
@cantebigene why do you consider this values as secret? this are default users and default as found in every installed fpm package. there is most of the time a wwwrun or a www-data user depending on the system.

for me this looks like a "scanner-script" that just looks for the string `user` and the string `key` which are correctly used here.  have you really read the output of the tool you have used?
