### ISSUE TITLE
Is it possible to ensure the fpm service from hiera?

### ISSUE THREAD

**Issue by jamesj2** [voxpupuli/puppet-php#609]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.8
- Ruby: 2.4.4p296
- Distribution: docker
- Module version: 7.1.0

## How to reproduce (e.g Puppet code you use)
Hiera:
```
php::fpm_service_enable: false
php::fpm_service_ensure: null
```
Manifest:
```
include ::php
```

## What are you seeing
Module starts FPM service every puppet run.  Unable to unset the ensure parameter for the php fpm service.  I use corosync/pacemaker to manage this service and sometimes it's running and sometimes it's not.

## What behaviour did you expect instead
FPM service should not start

## Output log
Notice: /Stage[main]/Php::Fpm::Service/Service[php74-php-fpm]/ensure: ensure changed 'stopped' to 'running' (corrective)

## Any additional information you'd like to impart
The php::fpm_service_enable setting works but the php::fpm_service_ensure always is overwritten with the default of "running".

**Comment by kenyon** [comment]
@jamesj2 `null` is not one of the options for `ensure` on services: https://puppet.com/docs/puppet/latest/types/service.html#service-attribute-ensure

You can also set `enable` to `mask` to prevent the service from starting, assuming systemd.

**Comment by jamesj2** [comment]
I made a fork and used lookup() to use hiera as the default and use the params if it's not present.  But your solution would work, I didn't think of that.  Thanks!
