### ISSUE TITLE
remove puppet 5 support, introduce puppet 7 support

### ISSUE THREAD

**Issue by attachmentgenie** [voxpupuli/puppet-php#616]
this module currently supports a old puppet matrix this should be brought into line with other modules

**Comment by c33s** [comment]
why? as debian stable currently ships a supported 5.5 version.
why the version rush? https://packages.debian.org/buster/puppet

**Comment by attachmentgenie** [comment]
see voxpupuli/voxpupuli.github.io/issues/229

**Comment by attachmentgenie** [comment]
merged in #632
