### ISSUE TITLE
PECL/Extension checks for beta packages

### ISSUE THREAD

**Issue by pkordylewski** [voxpupuli/puppet-php#73]
Howdy,

i have the following hiera file (snippet):

```
php::extensions:
  geoip:
    provider: pecl
```

When i run puppet multiple times i always get:

```
Notice: /Stage[main]/Php/Php::Extension[geoip]/Package[pecl-geoip]/ensure: ensure changed '1.0.8' to '1.1.0'
```

The installed version is still 1.0.8:

```
Package   Version State
geoip     1.0.8   stable
```

Version 1.1.0 of geoip is in beta state. I get the same with other packages (e.g. memcache).

Is this a hiera configuration mistake by me?

Thanks,
Patryk

**Comment by fpletz** [comment]
If I remember correctly this is a problem with the information we can get from pecl in the pecl package provider. @globin what's your take on this?

@pkordylewski As a quick fix, you could try to set the `ensure` parameter of the extension to the specific version `'1.0.8'`.

**Comment by pkordylewski** [comment]
Hi,

sorry for my late response. Your quick fix does work for the pecl provider. But for pear packages (like Benchmark or Phing) this doesn't work. I'm a bit confused why i'm using the not documented "pear" provider... :-(

```
php::extensions:
  phing:
    provider: pear
    source: pear.phing.info/phing
  benchmark:
    provider: pear
    source: pear.php.net/benchmark
```

But "ensure: VERSION" has no effect for "pear" provider. I still get on every run:

```
Notice: /Stage[main]/Php/Php::Extension[benchmark]/Package[php5-benchmark]/ensure: created
Info: Php::Extension[benchmark]: Scheduling refresh of Service[php5-fpm]
Notice: /Stage[main]/Php/Php::Extension[phing]/Package[php5-phing]/ensure: created
Info: Php::Extension[phing]: Scheduling refresh of Service[php5-fpm]
Notice: /Stage[main]/Php::Fpm::Service/Service[php5-fpm]: Triggered 'refresh' from 2 events
```

Any hints?

Thanks,
Patryk

**Comment by pkordylewski** [comment]
Any news on this?

**Comment by fpletz** [comment]
Sorry, we currently don't have time to fix this.

**Comment by leshiynyc** [comment]
Hi, 

Any update on this ?

**Comment by SimonHoenscheid** [comment]
Is this still a thing? Otherwise please close
